name: Deploy to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  deploy:
     uses: GY-CODING/.github/.github/workflows/github-packages-deploy.yml@master
     with:
       workspace: ${{ github.workspace }}
     secrets: inherit
